config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get 'users/login' => 'authentications#login', as: :login
  get "callback_handler" => 'home#callback_handler'
  resources :users
  get 'users/:id/invite' => 'users#invite', as: :invite_user
  post 'users/add_login' => 'authentications#add_login', as: :add_login
  post 'users/add_verification' => 'authentications#add_verification', as: :add_verification
  post 'users/add_two_way_sms_verification' => 'authentications#add_two_way_sms_verification', as: :add_two_way_sms_verification
  post 'users/add_totp' => 'authentications#add_totp', as: :add_totp
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  DEFAULT_VALUES = { status_id: 1, status_timeout: 0}
  validates :first_name, :last_name, :user_login, :company_id, :email, :phone,
            :person_id, :status_id, :status_timeout, presence: true
  validates :phone, presence: true, numericality: true,
                 :length => { :minimum => 10, :maximum => 15 }
  validates :company_id, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def login
  end

  def add_login
    @user = User.find_by_user_login(authentication_params[:user_login])
    if @user.present?
      params = {
        "strEndUsername" => @user.user_login,
        "strPCFingerprint" => request.user_agent,
        "strIPAddress" => request.ip,
        "strService" => "Web Access",
        "nMethod" => 1,
        "bAsHTML" => false
      }
      response = Spriv::Client.new.add_login(params)
      response = Spriv::Poller.new.get_decision(response['ID'])
      set_flash(response)
    else
      flash[:danger] = 'Unable to find user with this login'
    end
    redirect_to login_path

  end

  def add_verification
    @user = User.find_by_user_login(authentication_params[:user_login])
    if @user.present?
      params = {
        "strEndUsername" => @user.user_login,
        "strPCFingerprint" => request.user_agent,
        "strIPAddress" => request.ip,
        "strService" => "Web Access",
        "nMethod" => 1,
        "bAsHTML" => false,
        "strMessage" => 'Hello There Dev'
      }
      response = Spriv::Client.new.add_verification(params)
      response = Spriv::Poller.new.get_decision(response['ID'])
      set_flash(response)
    else
      flash[:danger] = 'Unable to find user with this login'
    end
    redirect_to login_path
  end

  def add_two_way_sms_verification
    @user = User.find_by_user_login(authentication_params[:user_login])
    if @user.present?
      params = {
        "strEndUsername" => @user.user_login,
        "strPCFingerprint" => request.user_agent,
        "strIPAddress" => request.ip,
        "strService" => "Web Access",
        "nMethod" => 2,
        "bAsHTML" => false,
        "strMessage" => 'Hello There Naiya!!'
      }
      response = Spriv::Client.new.add_verification(params)
      response = Spriv::Poller.new.get_decision(response['ID'])
      set_flash(response)
    else
      flash[:danger] = 'Unable to find user with this login'
    end
    redirect_to login_path
  end

  def add_totp
    @user = User.find_by_user_login(authentication_params[:user_login])
    if @user.present?
      params = {
        "strEndUsername" => @user.user_login,
        "strKey" => authentication_params[:key],
        "strIPAddress" => request.ip,
        "strService" => "Web Access",
        "nMethod" => 1,
        "bAsHTML" => false
      }
      response = Spriv::Client.new.add_totp(params)
      set_flash(response)
    else
      flash[:danger] = 'Unable to find user with this login'
    end
    redirect_to login_path
  end

  private

  def authentication_params
    params.require(:authentication).permit!
  end

  def set_flash(response)
    if response['Decision'] == 1
      flash[:success] = "Authentication Done successfully"
    elsif response['Decision'] == 3
      flash[:danger] = "Authentication Denied."
    elsif response['Message'] == 'OK'
      flash[:success] = "Authentication Done successfully"
    elsif response['Message'].match(/Wrong TOTP/)
      flash[:danger] = "Wrong TOTP code, please try again"
    else
      flash[:danger] = "Unable to Get response from Azure"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :assign_user, only: [:edit, :update, :destroy, :invite]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params.merge!(User::DEFAULT_VALUES))
    params = add_user_to_company(@user)

    response = Spriv::Client.new.add_user_to_company(params)
    if response['Info'].present?
      @user.reference_id = response['Info']
      @user.as_html = true
      if @user.save
        flash.now[:success] = "User added successfully"
        redirect_to users_path
      else
        flash.now[:danger] = @user.errors.full_messages
        render :new
      end
    else
      flash[:danger] = response['Message']
      render :new
    end
  end

  def edit
  end

  def update
    response = Spriv::Client.new.update_company_end_user(update_company_end_user)
    if response["Result"] == "Success"
      if @user.update_attributes(user_params)
        flash.now[:success] = "User updated successfully"
        redirect_to users_path
      else
        flash.now[:danger] = @user.errors.full_messages
        render :edit
      end
    else
      flash.now[:danger] = response['Message']
      render :edit
    end
  end

  def show
  end

  def destroy
    response = Spriv::Client.new.delete_end_user_from_company({ "lID" => @user.reference_id })
    if response["Result"] == "Success"
      if @user.destroy
        flash.now[:success] = "User Removed successfully"
      else
        flash.now[:danger] = "Unable to Remove user"
      end
    else
      flash.now[:danger] = "Unable to remove user from Spriv. Please try again after some time."
    end
    redirect_to users_path
  end

  def invite
    response = Spriv::Client.new.send_invitation({ "strEndUsers" => @user.reference_id })
    if response["Result"] == 'Success'
      flash.now[:success] = 'User invited successfully.'
    else
      flash.now[:danger] = "Unable to invite new user. Please try again."
    end
    redirect_to users_path
  end

  private

  def add_user_to_company(user)
    {
        "strAccount" => user.user_login,
        "nClientID" => user.company_id,
        "strFirstName" => user.first_name,
        "strLastName" => user.last_name,
        "strEmail" => user.email,
        "strMobilePhone" => user.phone,
        "bAsHTML" => true,
        "strPersonID" => user.person_id,
        "nStatusID" => user.status_id,
        "nStatusTimeout" => user.status_timeout,
      }

  end

  def update_company_end_user
    {
        "lID" => @user.reference_id,
        "strAccount" => user_params[:user_login],
        "nClientID" => user_params[:company_id],
        "strFirstName" => user_params[:first_name],
        "strLastName" => user_params[:last_name],
        "strEmail" => user_params[:email],
        "strMobilePhone" => user_params[:phone],
        "bAsHTML" => true,
        "strPersonID" => user_params[:person_id],
        "nStatusID" => @user.status_id,
        "nStatusTimeout" => @user.status_timeout,
        "bPaired" => true,
        "bLockedOut" => false
      }

  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_login,
      :company_id, :email, :phone, :person_id, :as_html
    )
  end

  def assign_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentications/login.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h3>Adaptive Two Factor Authentication</h3>
    <%= form_tag(add_login_path) do %>
    <div class="form-group">
      <label>Login ID</label>
        <%= text_field_tag 'authentication[user_login]', nil, placeholder: 'Enter Your Login ID', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= submit_tag "Authenticate", class: 'btn btn-success' %>
      </div>
    <% end %>
    <hr>
    <h3>Allow / Deny Push Notification</h3>
    <%= form_tag(add_verification_path) do %>
        <div class="form-group">
          <label>Login ID</label>
          <%= text_field_tag 'authentication[user_login]', nil, placeholder: 'Enter Your Login ID', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= submit_tag "Authenticate", class: 'btn btn-success' %>
        </div>
    <% end %>
    <hr>
    <h3>Two Way SMS Authentication</h3>
    <%= form_tag(add_two_way_sms_verification_path) do %>
      <div class="form-group">
        <label>Login ID</label>
        <%= text_field_tag 'authentication[user_login]', nil, placeholder: 'Enter Your Login ID', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= submit_tag "Authenticate", class: 'btn btn-success' %>
      </div>
    <% end %>
    <hr>
    <h3>TOTP Authentication</h3>
    <%= form_tag(add_totp_path) do %>
      <div class="form-group">
        <label>Login ID</label>
        <%= text_field_tag 'authentication[user_login]', nil, placeholder: 'Enter Your Login ID', class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Enter OTP here</label>
        <%= text_field_tag 'authentication[key]', nil, placeholder: 'OTP', class: 'form-control' %>
        <small id="emailHelp" class="form-text text-muted error hide">Invlid TOTP format. Must be 6 digits.</small>
      </div>
      <%= submit_tag "Authenticate", class: 'btn btn-success' %>
    <% end %>
  </div>
</row>
<script>
  $('#authentication_key').change(function(e){
    var otp = e.target.value;
    if(otp.length != 6){
      $('#emailHelp').addClass('show')
      $('#emailHelp').removeClass('hide')
    }else{
      $('#emailHelp').removeClass('show')
      $('#emailHelp').addClass('hide')
    }
  })
</script>

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg|  %>
<ul class="flash-mmsg">
<% if msg.class == Array %>
  <% msg.each do |value| %>

      <li class="alert <%= 'alert-' + key%>">
        <%= value %>
      </li>
    <%end %>
  <% else %>
    <li class="alert <%= 'alert-' + key%>"><%= msg %></li>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse ">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Spriv App", root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav pull-right navbar-right">
      <li><%= link_to "Authentication Methods", login_path %></li>
      <li><%= link_to "User Management", users_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SprivApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <%= render 'layouts/flash'%>
      <%= yield %>
    <div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: 'First Name', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: 'Last Name', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <label for="exampleSelect1">User Login</label>
    <%= f.text_field :user_login, placeholder: 'User Login', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <label for="exampleSelect2">Company ID</label>
    <%= f.text_field :company_id, placeholder: 'Company ID', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <label for="exampleTextarea">Email</label>
    <%= f.text_field :email, placeholder: 'Email', class: 'form-control', required: true %>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">Phone Number</label>
    <%= f.text_field :phone, placeholder: 'Phone No.', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">Person ID</label>
    <%= f.text_field :person_id, placeholder: 'Person ID', class: 'form-control', required: true %>
  </div>
  <%= f.submit 'Save', class: "btn btn-primary"%>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Edit User</h1>
    <%= render partial: 'users/form'%>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-6"><h3>All Users</h3></div>
  <div class="col-sm-6 text-right"><%= link_to 'Add User', new_user_path, class: 'btn btn-success' %></div>
</div>

<table class='table'>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>User Login</th>
    <th>Company ID</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Person ID</th>
    <th>As HTML</th>
    <th>Actions</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.user_login %></td>
      <td><%= user.company_id %></td>
      <td><%= user.email %></td>
      <td><%= user.phone %></td>
      <td><%= user.person_id%></td>
      <td><%= user.as_html%></td>
      <td><%= link_to "Edit", edit_user_path(user)%> |
        <%= link_to "Delete", user_path(user), method: :delete %> |
        <%= link_to "Invite", invite_user_path(user) %>
      </td>
  <% end %>
</table>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Add User</h1>
    <%= render partial: 'users/form'%>
  </div>
</div>